### PR TITLE
CO-6488 CO-6490 increase db_pool_size

### PR DESCRIPTION
**Pull request by coupacooke**
## JIRA

* [CO-6488 Main JIRA ticket](https://coupadev.atlassian.net/browse/CO-6488)
* [CO-6490 JIRA propagation subtask](https://coupadev.atlassian.net/browse/CO-6490)

## Code reviewers

- [x] @autrejacoupa
- [x] @alokdnb 

## Summary of issue

Chef is throwing some 500 internal server errors

## Summary of change

Increase db_pool_size.  At this point it's hardcoded - I thought about making it an attribute but don't want to fiddle with it independently.

## Testing Approach

Relaunched in Chef DEV Frankfurt.  See [CO-6488 Main JIRA ticket](https://coupadev.atlassian.net/browse/CO-6488)

## Feature Test Options

- [x] No tests

### CODE REVIEW

**Comment by miroslawjaworski** [comment]
consider frankfurt devchf492srv1
<https://us-4.rightscale.com/acct/13465/servers/1375013004?instance_id=227612096004>
uptime
3 months, so not so bad. Also almost nothing happens in dev there.


-- 
Mirosław Jaworski | Senior Site Reliability Engineer | Coupa Software
(O) +353.(0)16.917.058 (M) +353.899.846.202

**Comment by alokdnb** [comment]
@coupacooke I was looking at the 500 error compare to number of good responses we are giving. small numbers suggest that we might have concurrency issues thats causing it. Most likely some bursting traffic. I think its a good idea to have an exponential back-off in our logic where we are reading value from data bag. /opt/coupa/bin/databag_viewer.rb

[root@ip-10-6-3-144 erchef]# sudo zgrep "status=200"  requests.log.5| wc -l
295574
[root@ip-10-6-3-144 erchef]# grep 'no_connections' crash.log* | wc -l
150

**Comment by alokdnb** [comment]
we can move with this fix.

**Comment by coupacooke** [comment]
[lockit v4.3.0] Merged via Lockit CLI on 2018-04-12 09:16:49.908693 -0700 PDT m=+5.097392801

**Pull request merged**
